### ISSUE TITLE
Fix CI/CD with Heroku

### ISSUE THREAD

**Issue by PalAditya** [dsciitbbs/iitbbsnewsapi#10]
As suspected by @apsknight , the CI/CD with Heroku doesn't exist anymore. Please fix this.
@apsknight would you like to do the needful? 🤔

**Comment by PalAditya** [comment]
Fixed as per commit `9495c45f3f79fdea8677433c8bdfe0bb1a1b0d01`

**Comment by apsknight** [comment]
Thanks @PalAditya for fixing Heroku CD.
