### ISSUE TITLE
Create endpoints to list updates from IIT Bhubaneswar Twitter handle.

### ISSUE THREAD

**Issue by apsknight** [dsciitbbs/iitbbsnewsapi#5]
Create an endpoint `/twitter` to list updates from `@iitbbs` twitter handle.

**Comment by Sai-Adarsh** [comment]
could you help me with it ?

**Comment by apsknight** [comment]
Hi @Sai-Adarsh 

Please look at official Twitter API docs for searching tweets. If you need any specifiec help, ping me on Gitter.
